exclude: CODEOWNERS
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    -   id: go-fmt
    -   id: go-imports
    -   id: go-cyclo
        args:
        - -ignore=factory
        - -over=12
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/daveshanley/vacuum
    rev: v0.7.0
    hooks:
    -   id: vacuum
        args:
        - -d
        files: "api/openapi-spec/openapi.yaml"
