name: Check that build succeeds & tests pass

on:
  pull_request:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    - env:
        GOPRIVATE: "github.com/recurohealth/*"
      run: |
        echo "${{secrets.NETRC}}" >> ~/.netrc
        go build cmd/server.go
    - name: Run Unit Tests
      id: unit
      run: make test
